2024-03-25 16:21:33,545 INFO    StreamThr :24056 [internal.py:wandb_internal():86] W&B internal server running at pid: 24056, started at: 2024-03-25 16:21:33.544320
2024-03-25 16:21:33,546 DEBUG   HandlerThread:24056 [handler.py:handle_request():146] handle_request: status
2024-03-25 16:21:33,552 INFO    WriterThread:24056 [datastore.py:open_for_write():87] open: C:\Users\dadou\Documents\Github\Advanced-Programming\Strategies\wandb\run-20240325_162133-wdu63jdo\run-wdu63jdo.wandb
2024-03-25 16:21:33,552 DEBUG   SenderThread:24056 [sender.py:send():378] send: header
2024-03-25 16:21:33,580 DEBUG   SenderThread:24056 [sender.py:send():378] send: run
2024-03-25 16:21:34,161 INFO    SenderThread:24056 [dir_watcher.py:__init__():211] watching files in: C:\Users\dadou\Documents\Github\Advanced-Programming\Strategies\wandb\run-20240325_162133-wdu63jdo\files
2024-03-25 16:21:34,162 INFO    SenderThread:24056 [sender.py:_start_run_threads():1099] run started: wdu63jdo with start time 1711380093.545824
2024-03-25 16:21:34,168 DEBUG   HandlerThread:24056 [handler.py:handle_request():146] handle_request: check_version
2024-03-25 16:21:34,168 DEBUG   SenderThread:24056 [sender.py:send_request():405] send_request: check_version
2024-03-25 16:21:34,509 DEBUG   HandlerThread:24056 [handler.py:handle_request():146] handle_request: run_start
2024-03-25 16:21:34,528 DEBUG   HandlerThread:24056 [system_info.py:__init__():26] System info init
2024-03-25 16:21:34,528 DEBUG   HandlerThread:24056 [system_info.py:__init__():41] System info init done
2024-03-25 16:21:34,528 INFO    HandlerThread:24056 [system_monitor.py:start():194] Starting system monitor
2024-03-25 16:21:34,529 INFO    SystemMonitor:24056 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-03-25 16:21:34,529 INFO    HandlerThread:24056 [system_monitor.py:probe():214] Collecting system info
2024-03-25 16:21:34,534 INFO    SystemMonitor:24056 [interfaces.py:start():190] Started cpu monitoring
2024-03-25 16:21:34,534 INFO    SystemMonitor:24056 [interfaces.py:start():190] Started disk monitoring
2024-03-25 16:21:34,534 INFO    SystemMonitor:24056 [interfaces.py:start():190] Started gpu monitoring
2024-03-25 16:21:34,543 INFO    SystemMonitor:24056 [interfaces.py:start():190] Started memory monitoring
2024-03-25 16:21:34,553 INFO    SystemMonitor:24056 [interfaces.py:start():190] Started network monitoring
2024-03-25 16:21:34,557 DEBUG   HandlerThread:24056 [system_info.py:probe():150] Probing system
2024-03-25 16:21:34,558 DEBUG   HandlerThread:24056 [system_info.py:_probe_git():135] Probing git
2024-03-25 16:21:34,611 DEBUG   HandlerThread:24056 [system_info.py:_probe_git():143] Probing git done
2024-03-25 16:21:34,611 DEBUG   HandlerThread:24056 [system_info.py:probe():198] Probing system done
2024-03-25 16:21:34,611 DEBUG   HandlerThread:24056 [system_monitor.py:probe():223] {'os': 'Windows-10-10.0.22635-SP0', 'python': '3.11.8', 'heartbeatAt': '2024-03-25T15:21:34.557755', 'startedAt': '2024-03-25T15:21:33.535770', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': 'C:\\Users\\dadou\\Documents\\Github\\Advanced-Programming\\Strategies\\Transformer_strategy.py', 'codePathLocal': 'Transformer_strategy.py', 'codePath': 'Strategies\\Transformer_strategy.py', 'git': {'remote': 'https://github.com/AnDuquenne/Advanced-Programming.git', 'commit': '8923abb2f4fdccd454713bc938429a9f7c4efb54'}, 'email': 'andreas_duquenne@hotmail.com', 'root': 'C:/Users/dadou/Documents/Github/Advanced-Programming', 'host': 'DESKTOP-MM17CI9', 'username': 'dadou', 'executable': 'C:\\Users\\dadou\\anaconda3\\envs\\Advanced-Programming\\python.exe', 'cpu_count': 6, 'cpu_count_logical': 12, 'cpu_freq': {'current': 3912.0, 'min': 0.0, 'max': 3912.0}, 'cpu_freq_per_core': [{'current': 3912.0, 'min': 0.0, 'max': 3912.0}], 'disk': {'/': {'total': 465.07911682128906, 'used': 375.5881576538086}}, 'gpu': 'NVIDIA GeForce RTX 3060', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3060', 'memory_total': 12884901888}], 'memory': {'total': 31.87225341796875}}
2024-03-25 16:21:34,611 INFO    HandlerThread:24056 [system_monitor.py:probe():224] Finished collecting system info
2024-03-25 16:21:34,611 INFO    HandlerThread:24056 [system_monitor.py:probe():227] Publishing system info
2024-03-25 16:21:34,611 DEBUG   HandlerThread:24056 [system_info.py:_save_conda():207] Saving list of conda packages installed into the current environment
2024-03-25 16:21:34,613 ERROR   HandlerThread:24056 [system_info.py:_save_conda():218] Error saving conda packages: [WinError 2] Le fichier spécifié est introuvable
Traceback (most recent call last):
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\sdk\internal\system\system_info.py", line 214, in _save_conda
    subprocess.call(
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable
2024-03-25 16:21:34,614 DEBUG   HandlerThread:24056 [system_info.py:_save_conda():219] Saving conda packages done
2024-03-25 16:21:34,615 INFO    HandlerThread:24056 [system_monitor.py:probe():229] Finished publishing system info
2024-03-25 16:21:34,618 DEBUG   SenderThread:24056 [sender.py:send():378] send: files
2024-03-25 16:21:34,618 INFO    SenderThread:24056 [sender.py:_save_file():1365] saving file wandb-metadata.json with policy now
2024-03-25 16:21:34,683 DEBUG   HandlerThread:24056 [handler.py:handle_request():146] handle_request: python_packages
2024-03-25 16:21:34,683 DEBUG   SenderThread:24056 [sender.py:send_request():405] send_request: python_packages
2024-03-25 16:21:34,684 DEBUG   HandlerThread:24056 [handler.py:handle_request():146] handle_request: stop_status
2024-03-25 16:21:34,685 DEBUG   SenderThread:24056 [sender.py:send_request():405] send_request: stop_status
2024-03-25 16:21:34,685 DEBUG   HandlerThread:24056 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-25 16:21:35,079 DEBUG   SenderThread:24056 [sender.py:send():378] send: telemetry
2024-03-25 16:21:35,173 INFO    Thread-16 :24056 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\dadou\Documents\Github\Advanced-Programming\Strategies\wandb\run-20240325_162133-wdu63jdo\files\output.log
2024-03-25 16:21:35,173 INFO    Thread-16 :24056 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\dadou\Documents\Github\Advanced-Programming\Strategies\wandb\run-20240325_162133-wdu63jdo\files\wandb-metadata.json
2024-03-25 16:21:35,173 INFO    Thread-16 :24056 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\dadou\Documents\Github\Advanced-Programming\Strategies\wandb\run-20240325_162133-wdu63jdo\files\conda-environment.yaml
2024-03-25 16:21:35,174 INFO    Thread-16 :24056 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\dadou\Documents\Github\Advanced-Programming\Strategies\wandb\run-20240325_162133-wdu63jdo\files\requirements.txt
2024-03-25 16:21:35,386 INFO    wandb-upload_0:24056 [upload_job.py:push():131] Uploaded file C:\Users\dadou\AppData\Local\Temp\tmpr81gjl0swandb\whn7vl3o-wandb-metadata.json
2024-03-25 16:21:37,197 INFO    Thread-16 :24056 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\dadou\Documents\Github\Advanced-Programming\Strategies\wandb\run-20240325_162133-wdu63jdo\files\output.log
2024-03-25 16:21:39,129 DEBUG   HandlerThread:24056 [handler.py:handle_request():146] handle_request: status_report
2024-03-25 16:21:44,178 DEBUG   HandlerThread:24056 [handler.py:handle_request():146] handle_request: status_report
2024-03-25 16:21:45,651 DEBUG   HandlerThread:24056 [handler.py:handle_request():146] handle_request: partial_history
2024-03-25 16:21:45,651 DEBUG   HandlerThread:24056 [handler.py:handle_request():146] handle_request: partial_history
2024-03-25 16:21:46,824 DEBUG   SenderThread:24056 [sender.py:send():378] send: exit
2024-03-25 16:21:46,824 INFO    SenderThread:24056 [sender.py:send_exit():585] handling exit code: 255
2024-03-25 16:21:46,824 INFO    SenderThread:24056 [sender.py:send_exit():587] handling runtime: 12
2024-03-25 16:21:46,824 INFO    SenderThread:24056 [sender.py:_save_file():1365] saving file wandb-summary.json with policy end
2024-03-25 16:21:46,824 INFO    SenderThread:24056 [sender.py:send_exit():593] send defer
2024-03-25 16:21:46,824 DEBUG   HandlerThread:24056 [handler.py:handle_request():146] handle_request: defer
2024-03-25 16:21:46,824 INFO    HandlerThread:24056 [handler.py:handle_request_defer():172] handle defer: 0
2024-03-25 16:21:46,824 DEBUG   SenderThread:24056 [sender.py:send_request():405] send_request: defer
2024-03-25 16:21:46,824 INFO    SenderThread:24056 [sender.py:send_request_defer():609] handle sender defer: 0
2024-03-25 16:21:46,824 INFO    SenderThread:24056 [sender.py:transition_state():613] send defer: 1
2024-03-25 16:21:46,825 DEBUG   HandlerThread:24056 [handler.py:handle_request():146] handle_request: defer
2024-03-25 16:21:46,825 INFO    HandlerThread:24056 [handler.py:handle_request_defer():172] handle defer: 1
2024-03-25 16:21:46,825 DEBUG   SenderThread:24056 [sender.py:send_request():405] send_request: defer
2024-03-25 16:21:46,825 INFO    SenderThread:24056 [sender.py:send_request_defer():609] handle sender defer: 1
2024-03-25 16:21:46,825 INFO    SenderThread:24056 [sender.py:transition_state():613] send defer: 2
2024-03-25 16:21:46,825 DEBUG   HandlerThread:24056 [handler.py:handle_request():146] handle_request: defer
2024-03-25 16:21:46,825 INFO    HandlerThread:24056 [handler.py:handle_request_defer():172] handle defer: 2
2024-03-25 16:21:46,825 INFO    HandlerThread:24056 [system_monitor.py:finish():203] Stopping system monitor
2024-03-25 16:21:46,833 DEBUG   SystemMonitor:24056 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-03-25 16:21:46,833 INFO    HandlerThread:24056 [interfaces.py:finish():202] Joined cpu monitor
2024-03-25 16:21:46,833 DEBUG   SystemMonitor:24056 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-03-25 16:21:46,833 INFO    HandlerThread:24056 [interfaces.py:finish():202] Joined disk monitor
2024-03-25 16:21:46,833 DEBUG   SystemMonitor:24056 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-03-25 16:21:46,886 INFO    HandlerThread:24056 [interfaces.py:finish():202] Joined gpu monitor
2024-03-25 16:21:46,886 INFO    HandlerThread:24056 [interfaces.py:finish():202] Joined memory monitor
2024-03-25 16:21:46,886 INFO    HandlerThread:24056 [interfaces.py:finish():202] Joined network monitor
2024-03-25 16:21:46,886 DEBUG   SenderThread:24056 [sender.py:send_request():405] send_request: defer
2024-03-25 16:21:46,886 INFO    SenderThread:24056 [sender.py:send_request_defer():609] handle sender defer: 2
2024-03-25 16:21:46,886 INFO    SenderThread:24056 [sender.py:transition_state():613] send defer: 3
2024-03-25 16:21:46,886 DEBUG   SenderThread:24056 [sender.py:send():378] send: stats
2024-03-25 16:21:46,886 DEBUG   HandlerThread:24056 [handler.py:handle_request():146] handle_request: defer
2024-03-25 16:21:46,887 INFO    HandlerThread:24056 [handler.py:handle_request_defer():172] handle defer: 3
2024-03-25 16:21:46,887 DEBUG   SenderThread:24056 [sender.py:send():378] send: history
2024-03-25 16:21:46,887 DEBUG   SenderThread:24056 [sender.py:send_request():405] send_request: summary_record
2024-03-25 16:21:46,888 INFO    SenderThread:24056 [sender.py:_save_file():1365] saving file wandb-summary.json with policy end
2024-03-25 16:21:46,888 DEBUG   SenderThread:24056 [sender.py:send_request():405] send_request: defer
2024-03-25 16:21:46,888 INFO    SenderThread:24056 [sender.py:send_request_defer():609] handle sender defer: 3
2024-03-25 16:21:46,888 INFO    SenderThread:24056 [sender.py:transition_state():613] send defer: 4
2024-03-25 16:21:46,888 DEBUG   HandlerThread:24056 [handler.py:handle_request():146] handle_request: defer
2024-03-25 16:21:46,888 INFO    HandlerThread:24056 [handler.py:handle_request_defer():172] handle defer: 4
2024-03-25 16:21:46,888 DEBUG   SenderThread:24056 [sender.py:send_request():405] send_request: defer
2024-03-25 16:21:46,888 INFO    SenderThread:24056 [sender.py:send_request_defer():609] handle sender defer: 4
2024-03-25 16:21:46,888 INFO    SenderThread:24056 [sender.py:transition_state():613] send defer: 5
2024-03-25 16:21:46,888 DEBUG   HandlerThread:24056 [handler.py:handle_request():146] handle_request: defer
2024-03-25 16:21:46,888 INFO    HandlerThread:24056 [handler.py:handle_request_defer():172] handle defer: 5
2024-03-25 16:21:46,889 DEBUG   SenderThread:24056 [sender.py:send():378] send: summary
2024-03-25 16:21:46,889 INFO    SenderThread:24056 [sender.py:_save_file():1365] saving file wandb-summary.json with policy end
2024-03-25 16:21:46,889 DEBUG   SenderThread:24056 [sender.py:send_request():405] send_request: defer
2024-03-25 16:21:46,889 INFO    SenderThread:24056 [sender.py:send_request_defer():609] handle sender defer: 5
2024-03-25 16:21:46,889 INFO    SenderThread:24056 [sender.py:transition_state():613] send defer: 6
2024-03-25 16:21:46,889 DEBUG   HandlerThread:24056 [handler.py:handle_request():146] handle_request: defer
2024-03-25 16:21:46,889 INFO    HandlerThread:24056 [handler.py:handle_request_defer():172] handle defer: 6
2024-03-25 16:21:46,890 DEBUG   SenderThread:24056 [sender.py:send_request():405] send_request: defer
2024-03-25 16:21:46,890 INFO    SenderThread:24056 [sender.py:send_request_defer():609] handle sender defer: 6
2024-03-25 16:21:46,893 DEBUG   HandlerThread:24056 [handler.py:handle_request():146] handle_request: status_report
2024-03-25 16:21:47,040 INFO    SenderThread:24056 [sender.py:transition_state():613] send defer: 7
2024-03-25 16:21:47,041 DEBUG   HandlerThread:24056 [handler.py:handle_request():146] handle_request: defer
2024-03-25 16:21:47,041 INFO    HandlerThread:24056 [handler.py:handle_request_defer():172] handle defer: 7
2024-03-25 16:21:47,041 DEBUG   SenderThread:24056 [sender.py:send_request():405] send_request: defer
2024-03-25 16:21:47,041 INFO    SenderThread:24056 [sender.py:send_request_defer():609] handle sender defer: 7
2024-03-25 16:21:47,314 INFO    Thread-16 :24056 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\dadou\Documents\Github\Advanced-Programming\Strategies\wandb\run-20240325_162133-wdu63jdo\files\config.yaml
2024-03-25 16:21:47,314 INFO    Thread-16 :24056 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\dadou\Documents\Github\Advanced-Programming\Strategies\wandb\run-20240325_162133-wdu63jdo\files\output.log
2024-03-25 16:21:47,314 INFO    Thread-16 :24056 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\dadou\Documents\Github\Advanced-Programming\Strategies\wandb\run-20240325_162133-wdu63jdo\files\wandb-summary.json
2024-03-25 16:21:47,834 DEBUG   HandlerThread:24056 [handler.py:handle_request():146] handle_request: poll_exit
2024-03-25 16:21:49,329 INFO    Thread-16 :24056 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\dadou\Documents\Github\Advanced-Programming\Strategies\wandb\run-20240325_162133-wdu63jdo\files\output.log
2024-03-25 16:21:50,770 INFO    SenderThread:24056 [sender.py:transition_state():613] send defer: 8
2024-03-25 16:21:50,771 DEBUG   SenderThread:24056 [sender.py:send_request():405] send_request: poll_exit
2024-03-25 16:21:50,771 DEBUG   HandlerThread:24056 [handler.py:handle_request():146] handle_request: defer
2024-03-25 16:21:50,771 INFO    HandlerThread:24056 [handler.py:handle_request_defer():172] handle defer: 8
2024-03-25 16:21:50,771 DEBUG   SenderThread:24056 [sender.py:send_request():405] send_request: defer
2024-03-25 16:21:50,771 INFO    SenderThread:24056 [sender.py:send_request_defer():609] handle sender defer: 8
2024-03-25 16:21:50,771 INFO    SenderThread:24056 [job_builder.py:build():298] Attempting to build job artifact
2024-03-25 16:21:50,772 INFO    SenderThread:24056 [job_builder.py:_get_source_type():428] is repo sourced job
2024-03-25 16:21:50,873 DEBUG   HandlerThread:24056 [handler.py:handle_request():146] handle_request: poll_exit
2024-03-25 16:21:51,079 INFO    SenderThread:24056 [job_builder.py:build():404] adding wandb-job metadata file
2024-03-25 16:21:51,092 INFO    SenderThread:24056 [sender.py:transition_state():613] send defer: 9
2024-03-25 16:21:51,092 DEBUG   SenderThread:24056 [sender.py:send_request():405] send_request: poll_exit
2024-03-25 16:21:51,092 DEBUG   HandlerThread:24056 [handler.py:handle_request():146] handle_request: defer
2024-03-25 16:21:51,092 INFO    HandlerThread:24056 [handler.py:handle_request_defer():172] handle defer: 9
2024-03-25 16:21:51,092 DEBUG   SenderThread:24056 [sender.py:send():378] send: artifact
2024-03-25 16:21:51,357 INFO    Thread-16 :24056 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\dadou\Documents\Github\Advanced-Programming\Strategies\wandb\run-20240325_162133-wdu63jdo\files\output.log
2024-03-25 16:21:51,886 DEBUG   HandlerThread:24056 [handler.py:handle_request():146] handle_request: poll_exit
2024-03-25 16:21:52,184 INFO    wandb-upload_0:24056 [upload_job.py:push():86] Skipped uploading C:\Users\dadou\AppData\Local\wandb\wandb\artifacts\staging\tmpvolbm74f
2024-03-25 16:21:52,414 INFO    wandb-upload_1:24056 [upload_job.py:push():89] Uploaded file C:\Users\dadou\AppData\Local\wandb\wandb\artifacts\staging\tmp1f28th8v
2024-03-25 16:21:53,496 INFO    SenderThread:24056 [sender.py:send_artifact():1443] sent artifact job-https___github.com_AnDuquenne_Advanced-Programming.git_Strategies_Transformer_strategy.py - {'id': 'QXJ0aWZhY3Q6NzcwMDU4NzQ3', 'state': 'PENDING', 'artifactSequence': {'id': 'QXJ0aWZhY3RDb2xsZWN0aW9uOjE1MjA4NjcxMA==', 'latestArtifact': {'id': 'QXJ0aWZhY3Q6NzcwMDU3MjU0', 'versionIndex': 3}}}
2024-03-25 16:21:53,497 DEBUG   SenderThread:24056 [sender.py:send_request():405] send_request: defer
2024-03-25 16:21:53,497 INFO    SenderThread:24056 [sender.py:send_request_defer():609] handle sender defer: 9
2024-03-25 16:21:53,498 INFO    SenderThread:24056 [dir_watcher.py:finish():358] shutting down directory watcher
2024-03-25 16:21:54,392 INFO    SenderThread:24056 [dir_watcher.py:finish():388] scan: C:\Users\dadou\Documents\Github\Advanced-Programming\Strategies\wandb\run-20240325_162133-wdu63jdo\files
2024-03-25 16:21:54,393 INFO    SenderThread:24056 [dir_watcher.py:finish():402] scan save: C:\Users\dadou\Documents\Github\Advanced-Programming\Strategies\wandb\run-20240325_162133-wdu63jdo\files\conda-environment.yaml conda-environment.yaml
2024-03-25 16:21:54,393 INFO    SenderThread:24056 [dir_watcher.py:finish():402] scan save: C:\Users\dadou\Documents\Github\Advanced-Programming\Strategies\wandb\run-20240325_162133-wdu63jdo\files\config.yaml config.yaml
2024-03-25 16:21:54,393 INFO    SenderThread:24056 [dir_watcher.py:finish():402] scan save: C:\Users\dadou\Documents\Github\Advanced-Programming\Strategies\wandb\run-20240325_162133-wdu63jdo\files\output.log output.log
2024-03-25 16:21:54,393 INFO    SenderThread:24056 [dir_watcher.py:finish():402] scan save: C:\Users\dadou\Documents\Github\Advanced-Programming\Strategies\wandb\run-20240325_162133-wdu63jdo\files\requirements.txt requirements.txt
2024-03-25 16:21:54,394 INFO    SenderThread:24056 [dir_watcher.py:finish():402] scan save: C:\Users\dadou\Documents\Github\Advanced-Programming\Strategies\wandb\run-20240325_162133-wdu63jdo\files\wandb-metadata.json wandb-metadata.json
2024-03-25 16:21:54,396 INFO    SenderThread:24056 [dir_watcher.py:finish():402] scan save: C:\Users\dadou\Documents\Github\Advanced-Programming\Strategies\wandb\run-20240325_162133-wdu63jdo\files\wandb-summary.json wandb-summary.json
2024-03-25 16:21:54,397 INFO    SenderThread:24056 [sender.py:transition_state():613] send defer: 10
2024-03-25 16:21:54,397 DEBUG   SenderThread:24056 [sender.py:send_request():405] send_request: poll_exit
2024-03-25 16:21:54,398 DEBUG   HandlerThread:24056 [handler.py:handle_request():146] handle_request: defer
2024-03-25 16:21:54,398 INFO    HandlerThread:24056 [handler.py:handle_request_defer():172] handle defer: 10
2024-03-25 16:21:54,398 DEBUG   SenderThread:24056 [sender.py:send_request():405] send_request: defer
2024-03-25 16:21:54,398 INFO    SenderThread:24056 [sender.py:send_request_defer():609] handle sender defer: 10
2024-03-25 16:21:54,399 INFO    SenderThread:24056 [file_pusher.py:finish():172] shutting down file pusher
2024-03-25 16:21:54,537 ERROR   wandb-upload_1:24056 [internal_api.py:execute():373] 404 response executing GraphQL.
2024-03-25 16:21:54,537 ERROR   wandb-upload_1:24056 [internal_api.py:execute():374] {"errors":[{"message":"run stock_forecasting/wdu63jdo not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-03-25 16:21:54,537 ERROR   Thread-15 (_thread_body):24056 [step_upload.py:_handle_event():200] Failed to upload file: C:\Users\dadou\Documents\Github\Advanced-Programming\Strategies\wandb\run-20240325_162133-wdu63jdo\files\output.log
Traceback (most recent call last):
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\filesync\step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\filesync\step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\filesync\upload_job.py", line 57, in run
    self.push()
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\filesync\upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\apis\normalize.py", line 73, in wrapper
    raise err
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\apis\normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 2384, in upload_urls
    query_result = self.gql(
                   ^^^^^^^^^
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 341, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\sdk\lib\retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\util.py", line 910, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-03-25 16:21:54,541 ERROR   wandb-upload_0:24056 [internal_api.py:execute():373] 404 response executing GraphQL.
2024-03-25 16:21:54,544 ERROR   wandb-upload_0:24056 [internal_api.py:execute():374] {"errors":[{"message":"run stock_forecasting/wdu63jdo not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-03-25 16:21:54,544 ERROR   Thread-15 (_thread_body):24056 [step_upload.py:_handle_event():200] Failed to upload file: C:\Users\dadou\Documents\Github\Advanced-Programming\Strategies\wandb\run-20240325_162133-wdu63jdo\files\config.yaml
Traceback (most recent call last):
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\filesync\step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\filesync\step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\filesync\upload_job.py", line 57, in run
    self.push()
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\filesync\upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\apis\normalize.py", line 73, in wrapper
    raise err
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\apis\normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 2384, in upload_urls
    query_result = self.gql(
                   ^^^^^^^^^
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 341, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\sdk\lib\retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\util.py", line 910, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-03-25 16:21:54,852 ERROR   wandb-upload_3:24056 [internal_api.py:execute():373] 404 response executing GraphQL.
2024-03-25 16:21:54,852 ERROR   wandb-upload_3:24056 [internal_api.py:execute():374] {"errors":[{"message":"run stock_forecasting/wdu63jdo not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-03-25 16:21:54,852 ERROR   Thread-15 (_thread_body):24056 [step_upload.py:_handle_event():200] Failed to upload file: C:\Users\dadou\Documents\Github\Advanced-Programming\Strategies\wandb\run-20240325_162133-wdu63jdo\files\wandb-summary.json
Traceback (most recent call last):
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\filesync\step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\filesync\step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\filesync\upload_job.py", line 57, in run
    self.push()
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\filesync\upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\apis\normalize.py", line 73, in wrapper
    raise err
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\apis\normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 2384, in upload_urls
    query_result = self.gql(
                   ^^^^^^^^^
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 341, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\sdk\lib\retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\util.py", line 910, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-03-25 16:21:54,854 ERROR   wandb-upload_2:24056 [internal_api.py:execute():373] 404 response executing GraphQL.
2024-03-25 16:21:54,854 ERROR   wandb-upload_2:24056 [internal_api.py:execute():374] {"errors":[{"message":"run stock_forecasting/wdu63jdo not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-03-25 16:21:54,855 ERROR   Thread-15 (_thread_body):24056 [step_upload.py:_handle_event():200] Failed to upload file: C:\Users\dadou\Documents\Github\Advanced-Programming\Strategies\wandb\run-20240325_162133-wdu63jdo\files\requirements.txt
Traceback (most recent call last):
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\filesync\step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\filesync\step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\filesync\upload_job.py", line 57, in run
    self.push()
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\filesync\upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\apis\normalize.py", line 73, in wrapper
    raise err
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\apis\normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 2384, in upload_urls
    query_result = self.gql(
                   ^^^^^^^^^
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 341, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\sdk\lib\retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\dadou\anaconda3\envs\Advanced-Programming\Lib\site-packages\wandb\util.py", line 910, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-03-25 16:21:54,907 DEBUG   HandlerThread:24056 [handler.py:handle_request():146] handle_request: poll_exit
2024-03-25 16:21:54,908 DEBUG   SenderThread:24056 [sender.py:send_request():405] send_request: poll_exit
2024-03-25 16:21:55,064 INFO    Thread-15 (_thread_body):24056 [sender.py:transition_state():613] send defer: 11
2024-03-25 16:21:55,064 DEBUG   HandlerThread:24056 [handler.py:handle_request():146] handle_request: defer
2024-03-25 16:21:55,064 INFO    HandlerThread:24056 [handler.py:handle_request_defer():172] handle defer: 11
2024-03-25 16:21:55,064 DEBUG   SenderThread:24056 [sender.py:send_request():405] send_request: defer
2024-03-25 16:21:55,065 INFO    SenderThread:24056 [sender.py:send_request_defer():609] handle sender defer: 11
2024-03-25 16:21:55,065 INFO    SenderThread:24056 [file_pusher.py:join():178] waiting for file pusher
2024-03-25 16:21:55,065 INFO    SenderThread:24056 [sender.py:transition_state():613] send defer: 12
2024-03-25 16:21:55,066 DEBUG   HandlerThread:24056 [handler.py:handle_request():146] handle_request: defer
2024-03-25 16:21:55,066 INFO    HandlerThread:24056 [handler.py:handle_request_defer():172] handle defer: 12
2024-03-25 16:21:55,066 DEBUG   SenderThread:24056 [sender.py:send_request():405] send_request: defer
2024-03-25 16:21:55,066 INFO    SenderThread:24056 [sender.py:send_request_defer():609] handle sender defer: 12
2024-03-25 16:21:55,066 INFO    SenderThread:24056 [file_stream.py:finish():595] file stream finish called
2024-03-25 16:21:55,208 INFO    SenderThread:24056 [file_stream.py:finish():599] file stream finish is done
2024-03-25 16:21:55,208 INFO    SenderThread:24056 [sender.py:transition_state():613] send defer: 13
2024-03-25 16:21:55,208 DEBUG   HandlerThread:24056 [handler.py:handle_request():146] handle_request: defer
2024-03-25 16:21:55,208 INFO    HandlerThread:24056 [handler.py:handle_request_defer():172] handle defer: 13
2024-03-25 16:21:55,208 DEBUG   SenderThread:24056 [sender.py:send_request():405] send_request: defer
2024-03-25 16:21:55,208 INFO    SenderThread:24056 [sender.py:send_request_defer():609] handle sender defer: 13
2024-03-25 16:21:55,209 INFO    SenderThread:24056 [sender.py:transition_state():613] send defer: 14
2024-03-25 16:21:55,209 DEBUG   HandlerThread:24056 [handler.py:handle_request():146] handle_request: defer
2024-03-25 16:21:55,209 INFO    HandlerThread:24056 [handler.py:handle_request_defer():172] handle defer: 14
2024-03-25 16:21:55,209 DEBUG   SenderThread:24056 [sender.py:send():378] send: final
2024-03-25 16:21:55,209 DEBUG   SenderThread:24056 [sender.py:send():378] send: footer
2024-03-25 16:21:55,209 DEBUG   SenderThread:24056 [sender.py:send_request():405] send_request: defer
2024-03-25 16:21:55,209 INFO    SenderThread:24056 [sender.py:send_request_defer():609] handle sender defer: 14
2024-03-25 16:21:55,210 DEBUG   HandlerThread:24056 [handler.py:handle_request():146] handle_request: poll_exit
2024-03-25 16:21:55,210 DEBUG   HandlerThread:24056 [handler.py:handle_request():146] handle_request: poll_exit
2024-03-25 16:21:55,210 DEBUG   HandlerThread:24056 [handler.py:handle_request():146] handle_request: server_info
2024-03-25 16:21:55,210 DEBUG   HandlerThread:24056 [handler.py:handle_request():146] handle_request: get_summary
2024-03-25 16:21:55,210 DEBUG   SenderThread:24056 [sender.py:send_request():405] send_request: poll_exit
2024-03-25 16:21:55,210 DEBUG   HandlerThread:24056 [handler.py:handle_request():146] handle_request: sampled_history
2024-03-25 16:21:55,210 DEBUG   SenderThread:24056 [sender.py:send_request():405] send_request: poll_exit
2024-03-25 16:21:55,210 DEBUG   HandlerThread:24056 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-25 16:21:55,211 DEBUG   SenderThread:24056 [sender.py:send_request():405] send_request: server_info
2024-03-25 16:21:55,212 DEBUG   HandlerThread:24056 [handler.py:handle_request():146] handle_request: job_info
2024-03-25 16:21:55,359 DEBUG   SenderThread:24056 [sender.py:send_request():405] send_request: job_info
2024-03-25 16:21:55,359 INFO    MainThread:24056 [wandb_run.py:_footer_history_summary_info():3851] rendering history
2024-03-25 16:21:55,360 INFO    MainThread:24056 [wandb_run.py:_footer_history_summary_info():3883] rendering summary
2024-03-25 16:21:55,360 INFO    MainThread:24056 [wandb_run.py:_footer_sync_info():3810] logging synced files
2024-03-25 16:21:55,360 DEBUG   HandlerThread:24056 [handler.py:handle_request():146] handle_request: shutdown
2024-03-25 16:21:55,360 INFO    HandlerThread:24056 [handler.py:finish():869] shutting down handler
2024-03-25 16:21:56,220 INFO    WriterThread:24056 [datastore.py:close():296] close: C:\Users\dadou\Documents\Github\Advanced-Programming\Strategies\wandb\run-20240325_162133-wdu63jdo\run-wdu63jdo.wandb
2024-03-25 16:21:56,361 INFO    SenderThread:24056 [sender.py:finish():1521] shutting down sender
2024-03-25 16:21:56,361 INFO    SenderThread:24056 [file_pusher.py:finish():172] shutting down file pusher
2024-03-25 16:21:56,361 INFO    SenderThread:24056 [file_pusher.py:join():178] waiting for file pusher
